apiVersion: apps/v1
kind: Deployment
metadata:
  name: llull
  namespace: llull
  labels:
    app: llull
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llull
  template:
    metadata:
      labels:
        app: llull
    spec:
      containers:
        - name: llull
          image: llull:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llull-secret
                  key: auth-token
          livenessProbe:
            httpGet:
              path: /v1/health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      restartPolicy: Always
