apiVersion: v1
kind: Service
metadata:
  name: llull-searchengine
  namespace: llull
spec:
  selector:
    app: llull-searchengine
  ports:
    - port: 8080
      targetPort: http
      name: http
  type: ClusterIP
